### ISSUE TITLE
Run Spectral as part of the action

### ISSUE THREAD

**Issue by njenia** [SpectralOps/spectral-github-action#1]
Hi @guylev008 , great work!
Is there a reason why there are 2 separate steps, one for installing and second for running?
It could be just:
```
    - name: Install and Run Spectral
      uses: spectralops/spectral-github-action@v1
      with:
        spectral-dsn: ${{ secrets.SPECTRAL_DSN }}
```
which would install **and** run spectral.
Maybe it's to be able to send arguments to spectral? then again, this could be send as parameters under `with:` of the single action.
