### ISSUE TITLE
error: Found argument '--ok' which wasn't expected, or isn't valid in this context

### ISSUE THREAD

**Issue by bennycode** [SpectralOps/spectral-github-action#5]
I am using this config:

```yml
      - name: Install Spectral
        uses: spectralops/spectral-github-action@v2
        with:
          spectral-dsn: ${{ env.SPECTRAL_DSN }}
          spectral-args: --ok
      - name: Run Spectral
        run: spectral scan --github-format
```

Unfortunately my action fails with error message:

> error: Found argument '--ok' which wasn't expected, or isn't valid in this context

Am I holding it wrong? The `spectral-args` with `--ok` is documented here: https://github.com/SpectralOps/spectral-github-action/tree/v2#configuration
