### ISSUE TITLE
Configure fail severity

### ISSUE THREAD

**Issue by bennycode** [SpectralOps/spectral-github-action#8]
Spectral's dashboard breaks issues down into errors, warnings & info. 

I am using the following setup in my CI environment:

```yml
  spectral-code-scan:
    needs: [cancel-previous]
    runs-on: ubuntu-latest
    env:
      SPECTRAL_DSN: ${{ secrets.SPECTRAL_DSN }}
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run Spectral (Base)
        uses: spectralops/spectral-github-action@v2
        with:
          spectral-dsn: ${{ env.SPECTRAL_DSN }}
          spectral-args: scan --github-format --include-tags base,audit
```

Unfortunately, this configuration makes my builds fail on simple warnings like this:

> Warning: Environment configuration file [SENF073]

I don't want to use the `--ok` flag because this would also let severe errors pass. Is there a way to specify Spectral's GitHub Action to not fail on warnings?
