### ISSUE TITLE
Error: TypeError [ERR_INVALID_URL]: Invalid URL: /latest/dl/linux

### ISSUE THREAD

**Issue by igrek8** [SpectralOps/spectral-github-action#9]
For some reason github action errors: with 

`Error: TypeError [ERR_INVALID_URL]: Invalid URL: /latest/dl/linux`

```yml
name: Scan code

on:
  pull_request:
    branches:
      - main

env:
  SPECTRAL_DSN: ${{ secrets.SPECTRAL_DSN }}

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: spectralops/spectral-github-action@v2
        with:
          spectral-dsn: ${{ env.SPECTRAL_DSN }}
          spectral-args: scan --fail-on-error --github-format --include-tags base,audit
```

<img width="828" alt="image" src="https://user-images.githubusercontent.com/7078731/194025506-b4e615a9-205a-4d6e-8169-19059bb266b1.png">
